name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  TESTS_ENABLED: "false"
jobs:
  publish:
    name: Publish module to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
          scope: "imogen-deeptech"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Prepare playground for automated testing
        run: npm run dev:prepare
        if: ${{  env.TESTS_ENABLED == 'true' }}

      - name: Run tests
        run: npm run test
        if: ${{  env.TESTS_ENABLED == 'true' }}

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
